trigger:
- master

pr: none

jobs:
- job: deploy_prod
  pool:
    vmImage: 'Ubuntu-16.04'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.12'
  - script: |
      echo "//registry.npmjs.org/:_authToken=$(NPM-TOKEN)" > ~/.npmrc
      yarn
      yarn build
    displayName: Build
  - script: |
      yarn release
    displayName: Deploy

