trigger:
- master

pr: none

variables:
  - group: AzureKeyVaults

jobs:
- job: deploy_prod
  pool:
    vmImage: 'Ubuntu-16.04'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
  - script: |
      yarn
    displayName: Build
  - script: |
      npm config set "//registry.npmjs.org/:_authToken=$(NPM-TOKEN)"
      yarn release patch
    displayName: Deploy

