trigger:
- master

pr: none

jobs:
- job: deploy_prod
  pool:
    vmImage: 'Ubuntu-16.04'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.12'
  - script: |
      echo "//registry.npmjs.org/:_authToken=$(NPM-TOKEN)" > ~/.npmrc
      cp ~/.npmrc ./
      yarn
      yarn build
    displayName: Build
  - script: |
      export GITHUB_TOKEN=$(GITHUB-TOKEN)
      git config --global user.email "bot@zigbang.com"
      git config --global user.name "zigbang_bot"
      yarn release
    displayName: Deploy

