trigger:
- master

pr: none

jobs:
- job: deploy_prod
  pool:
    vmImage: 'Ubuntu-16.04'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
  - script: |
      yarn
    displayName: Build
  - script: |
      echo "//registry.npmjs.org/:_authToken=$(NPM-TOKEN)" > ~/.npmrc
      git config --global user.email "bot@zigbang.com"
      git config --global user.name "Zigbang BOT"
      npm version patch && git push
      yarn deploy
    displayName: Deploy

