trigger:
- master

pr: none

jobs:
- job: deploy_prod
  pool:
    vmImage: 'Ubuntu-16.04'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  steps:
  - task: NodeTool@0
  - script: |
      yarn
    displayName: Build
  - script: |
      yarn deploy
    displayName: Deploy

