version: 2.1

commands:
  common:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "02:b5:b3:06:7f:af:06:8a:37:c1:22:85:fa:22:10:2d"
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: lerna bootstrap
          command: lerna bootstrap

jobs:
  zigbang:
    docker:
      - image: zigbang/node
    working_directory: ~/repo
    steps:
      - checkout
      - common
      - clone-repo:
          repo_url: git@bitbucket.org:zigbang/zigbang.git
          repo_name: zigbang
          target_branch: release
      - tslint-reports:
          repo_name: zigbang
  zigbang-api:
    docker:
      - image: zigbang/node
    working_directory: ~/repo
    steps:
      - checkout
      - common
      - clone-repo:
          repo_url: git@bitbucket.org:zigbang/zigbang-api.git
          repo_name: zigbang-api
          target_branch: master
      - tslint-reports:
          repo_name: zigbang-api
  zigbang-apis-v2:
    docker:
      - image: zigbang/node
    working_directory: ~/repo
    steps:
      - checkout
      - common
      - clone-repo:
          repo_url: git@bitbucket.org:zigbang/zigbang-apis-v2.git
          repo_name: zigbang-apis-v2
          target_branch: master
      - tslint-reports:
          repo_name: zigbang-apis-v2
  zigbang-io:
    docker:
      - image: zigbang/node
    working_directory: ~/repo
    steps:
      - checkout
      - common
      - clone-repo:
          repo_url: git@bitbucket.org:zigbang/zigbang-io.git
          repo_name: zigbang-io
          target_branch: master
      - tslint-reports:
          repo_name: zigbang-io
  react-zuix:
    docker:
      - image: zigbang/node
    working_directory: ~/repo
    steps:
      - checkout
      - common
      - clone-repo:
          repo_url: git@bitbucket.org:zigbang/react-zuix.git
          repo_name: react-zuix
          target_branch: master
      - lint-repo:
          repo_name: react-zuix
          prettier_src: '"./**/*.{ts,tsx}"'
          prettier_config: ./prettier.config.js
          project_path: ./
          tslint_config: ./tslint.json
      - tslint-reports:
          repo_name: react-zuix
  zigbang-utils:
    docker:
      - image: zigbang/node
    working_directory: ~/repo
    steps:
      - checkout
      - common
      - clone-repo:
          repo_url: git@bitbucket.org:zigbang/zigbang-utils.git
          repo_name: zigbang-utils
          target_branch: master
      - tslint-reports:
          repo_name: zigbang-utils
  summary:
    docker:
      - image: zigbang/node
    working_directory: ~/repo
    steps:
      - checkout
      - common
      - attach_workspace:
          at: ./sub/.results
      - tslint-summary
      - store_artifacts:
          path: ./sub/.results/result.json


workflows:
  version: 2.1
  nightly:
    jobs:
      - zigbang
      - zigbang-api
      - zigbang-apis-v2
      - zigbang-io
      - react-zuix
      - zigbang-utils
      - summary:
          requires:
            - zigbang
            - zigbang-api
            - zigbang-apis-v2
            - zigbang-io
            - react-zuix
            - zigbang-utils
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - /master/
